/* dropTables.sql - permanently delete all tables from sqlite3 db.  THIS IS INTENDED ONLY FOR DEVELOPMENT. */

DROP TABLE UM_MEMBER;
DROP TABLE DESC_ORG_GROUPS;
DROP TABLE DESC_ORG_ROLES;
DROP TABLE DESC_ORG_AUTHORITIES;
DROP TABLE DESC_SERVICE_HIST;
